language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - yarn global add @angular/cli
script:
- yarn lint
- yarn test-headless
- yarn travis-deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/rdm-pwa
  on:
    branch: master
