language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
# acredito não ser necessário instalar o angular/cli globarl ... ele vai como dev dependency
before_script:
  - yarn global add @angular/cli
script:
- yarn lint
- yarn test-headless
- yarn build-ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
