language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
# acredito não ser necessário instalar o angular/cli globarl ... ele vai como dev dependency
before_script:
  - yarn global add @angular/cli
script:
- yarn lint
- yarn test-headless
- yarn ci-build-gh
- yarn ci-deploy-gh
