version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn global add @angular/cli
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "reidamesa.com" > public/CNAME
      - run: yarn lint
      - run: yarn test-headless
      - run: yarn ci-build-gh
      - run: yarn ci-deploy-gh

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/7c3f9e72-9a05-4957-ac25-4c2b1cc2363a@2c0780e1-70da-488e-ad69-94c0e6bee8d0/CircleCI/e04486446d7849a2ab8fa9a802f661de/25f564fe-f768-41b6-97bf-28458eb11464
