version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn global add @angular/cli
      # - run: yarn lint
      # - run: yarn test-headless
      - run: yarn build-ci
      - run: echo ${GITHUB_TOKEN}
      - run: echo https://${GITHUB_TOKEN}@github.com/rpgaudioso/rdm-pwa.git
      - run: npx ngh --repo="https://${GITHUB_TOKEN}@github.com/rpgaudioso/rdm-pwa.git" --name="rpgaudioso" --email=rpgaudioso@gmail.com --no-silent=true
      # - run: npx ngh --token=$GITHUB_TOKEN --name="rpgaudioso" --email=rpgaudioso@gmail.com --no-silent=true
